@backend_HostAddress = https://localhost:7141

GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{backend_HostAddress}}/weatherforecast

###

POST {{backend_HostAddress}}/api/auth/google
Content-Type: application/json

{
  "idToken": "token_falso"
}

###
